services:
  mssqldb:
    ports:
      - 1433:1433
    volumes:
      - mssql-db:/var/opt/mssql
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - gateway_service_network
  
  redisdb:
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data
    environment:
      REQUIREPASS: ${REDIS_PASSWORD}
      
  zookeeper:
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - gateway_service_network

  kafka:
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - gateway_service_network
    depends_on:
      - zookeeper