services:
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    
  redisdb:
    container_name: redisdb
    image: redis:latest
    restart: always
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    
volumes:
  mssql-db:
  redis-db: